### ISSUE TITLE
any guide, document or paper on this project?

### ISSUE THREAD

**Issue by SeekPoint** [phuongnm-bkhn/deeplearnning-NN-nlp-NER#1]

**Comment by phuongnm94** [comment]
you can see here : 
https://github.com/Element-Research/rnn/blob/master/examples/simple-recurrent-network.lua
https://github.com/Element-Research/rnn/blob/master/examples/simple-sequencer-network.lua
paper can be find on google : 
https://www.cs.toronto.edu/~fritz/absps/RNN13.pdf
..
