### ISSUE TITLE
bad argument #2 to '?' (out of bounds at /home/rzai/torch/pkg/torch/lib/TH/generic/THStorage.c:202)

### ISSUE THREAD

**Issue by SeekPoint** [phuongnm-bkhn/deeplearnning-NN-nlp-NER#2]
rzai@rzai00:~/prj/deeplearnning-NN-nlp-NER/src$ th main.lua --nameLog xxx
{
  hasTimeLog : false
  batchSentenceSize : 30
  isUseFeatureWord : false
  isTrainBatchSentenceSameSize : false
  isUseOptimizeGradient : false
  lr : 0.1
  nameLog : "xxx"
  isSaveLog : false
  countLoopOneBatchSize : 5
  trainRate : 0.9
  countLoopAllData : 100
  iDataset : 5
  nameNet : "brnnLstm"
}
/home/rzai/torch/install/bin/luajit: bad argument #2 to '?' (out of bounds at /home/rzai/torch/pkg/torch/lib/TH/generic/THStorage.c:202)
stack traceback:
        [C]: at 0x7ff77a37a3d0
        [C]: in function '__index'
        ./InitData.lua:321: in function 'InitData'
        main.lua:65: in function 'main'
        main.lua:130: in main chunk
        [C]: in function 'dofile'
        ...rzai/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x00406670

**Comment by phuongnm94** [comment]
oh Sorry - I'm not update data of my company ("it is private!")! This is my first project with Lua, so it not perfect :))  I will update the trial data next week !!

**Comment by SeekPoint** [comment]
great job!

**Comment by kdatta03** [comment]
Sorry but what was done to solve this issue?
